Models/GalleryViewModel.cs
using PolyBook.Domain.Entities;
using System;
using System.Collections;
using System.Collections.Generic;

namespace PolyBook.Models
{
    public class GalleryViewModel
    {
        public GalleryViewModel(int num, string name, IEnumerable<Book> content)
        {
            GalleryNum = num;
            GalleryName = name;
            GalleryContentBooks = content;
        }

        public int GalleryNum { get; set; }
        public string GalleryName { get; set; }
        public IEnumerable<Book> GalleryContentBooks { get; set; }
    }
}

Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PolyBook.Domain;
using PolyBook.Domain.Entities;
using PolyBook.Models;
using PolyBook.Service;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PolyBook.Controllers
{
    public class BooksController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly AppDbContext context;
        public BooksController(DataManager dataManager, AppDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
            this.context = context;
        }

        public IActionResult Book(Guid id)
        {
            Book book = dataManager.Books.GetBookById(id);
            if (book == null) {return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());}
            return View("Book", book);
        }

        [Authorize]
        public IActionResult Edit(Guid id)
        {
            Book entity;
            if (id == default) { entity = new Book(); }
            else
            {
                entity = dataManager.Books.GetBookById(id);
                AppUser CurrentUser = context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
                string UserID = CurrentUser.Id;
                if (entity.OwnerID != Guid.Parse(UserID))
                {
                    if (!User.IsInRole("admin"))
                    {
                        return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
                    }
                }
            }
            return View(entity);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(Book model, IFormFile ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (model.OwnerID == default)
                {
                    AppUser CurrentUser = context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
                    string UserID = CurrentUser.Id;
                    model.OwnerID = Guid.Parse(UserID);
                }
                string BookOwnerID = model.OwnerID.ToString();
                AppUser BookOwner = context.Users.FirstOrDefault(x => x.Id == BookOwnerID);
                model.OwnerName = BookOwner.Name + " " + BookOwner.Surname;
                if (ImageFile != null)
                {
                    model.ImagePath = DateTime.Now.ToString("HHmmss") + BookOwner.Surname + ".png";
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "img/photos/", model.ImagePath), FileMode.Create))
                    {
                        ImageFile.CopyTo(stream);
                    }
                }
                dataManager.Books.SaveBook(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            AppUser CurrentUser = context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
            Book CurrentBook = context.Books.FirstOrDefault(x => x.Id == id);
            string UserID = CurrentUser.Id;

            if (CurrentBook.OwnerID != Guid.Parse(UserID))
            {
                if (!User.IsInRole("admin"))
                {
                    return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
                }
            }

            dataManager.Books.DeleteBook(CurrentBook);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Views/Shared/Components/EditButton/EditButtonViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using PolyBook.Domain;
using PolyBook.Domain.Entities;
using PolyBook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PolyBook.Views.Shared.Components
{
    public class EditButtonViewComponent : ViewComponent
    {
        private readonly AppDbContext context;
        public EditButtonViewComponent(AppDbContext context)
        {
            this.context = context;
        }

        public ViewViewComponentResult Invoke(Book book)
        {
            bool isOwner = false;
            AppUser CurrentUser = context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
            string UserID = CurrentUser.Id;
            if (book.OwnerID == Guid.Parse(UserID) || User.IsInRole("admin"))
            {
                isOwner = true;
            }
            return View(new EditButtonViewModel(book, isOwner));
        }

    }
}

Views/Shared/Components/Profile/ProfileViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using PolyBook.Domain;
using PolyBook.Domain.Entities;
using PolyBook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PolyBook.Views.Shared.Components
{
    public class ProfileViewComponent : ViewComponent
    {
        private readonly AppDbContext context;
        public ProfileViewComponent(AppDbContext context)
        {
            this.context = context;
        }

        public ViewViewComponentResult Invoke()
        {
            AppUser CurrentUser = context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
            string UserID = CurrentUser.Id;
            string UserName = CurrentUser.Name;
            string UserSurname = CurrentUser.Surname;
            string UserEmail = CurrentUser.Email;
            string UserImage = CurrentUser.Image;
            return View(new ProfileViewModel(UserID, UserName, UserSurname, UserEmail, UserImage));
        }

    }
}

Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/style0.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/style1.css" asp-append-version="true" />
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&family=Montserrat&display=swap" rel="stylesheet">

Views/Shared/Gallery.cshtml
@model GalleryViewModel

@{ 
    ViewData["Title"] = @Model.GalleryName;
}
<div class="contentblock">
    <h1>@Model.GalleryName</h1>
    <div id="gallerygrid">
            @foreach (var book in Model.GalleryContentBooks)
            {
                if (book.BookGallery == 0) { ViewData["GalleryColor"] = @Config.yellow; }
                if (book.BookGallery == 1) { ViewData["GalleryColor"] = @Config.red; }
                if (book.BookGallery == @Model.GalleryNum || (@Model.GalleryNum == 3))
                {
                    <div class="gallergridblock">
                        <a asp-area="" asp-controller="Books" asp-action="Book" asp-route-id="@book.Id">
                            <div class="post">
                                <div class="posticon" style="background-color:@ViewData["GalleryColor"];"></div>
                                <div class="postname">@book.Title</div>
                                <div class="postimg" style="border-top: solid 1px @ViewData["GalleryColor"];"><img class="photo" src="~/img/photos/@book.ImagePath" onError="this.src='../img/photos/0.png'" alt="photo"></div>
                                <div class="postinfo">
                                    <b>@book.OwnerName</b> <br>
                                    <b>Автор:</b> @book.Author<br>
                                    <b>Год:</b> @book.Year<br>
                                    <b>Тематика:</b> @book.Subject <br>
                                </div>
                            </div>
                        </a>
                    </div>
                }
            }
    </div>
</div>

Views/Shared/MetatagsPartial.cshtml
@using PolyBook.Service
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
@if (ViewBag.Title != null)
{
    <title>@ViewData["Title"]</title>
}
else
{
    <title>@Config.ProjectName</title>
}
@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await Html.PartialAsync("CssPartial")
</head>
<body>
    <main>
        <header>
            <a id="logo" asp-area="" asp-controller="Home" asp-action="Index">@Config.ProjectName</a>
            @if (User.Identity.IsAuthenticated){<a id="loginlink" asp-area="" asp-controller="Account" asp-action="Logout">Выйти</a>}
            else {<a id="loginlink" asp-area="" asp-controller="Account" asp-action="Login">Войти</a>}
        </header>
        <nav>
            <div id="profile">
                @if (User.Identity.IsAuthenticated)
                {
                    @await Component.InvokeAsync("Profile")
                }
                else
                {
                    <img id="profileimg" src="~/img/accounts/default.png" alt="logo">

                    <div id="profilewelcome">
                        <div>
                            <span class="profiletext" style="color: #b5b9c4;">Добро пожаловать</span><br />
                            <span class="profilemaintext">Вы не авторизованы</span><br />
                        </div>
                    </div>
                }
            </div>
            <div id="categories">
                <p class="title">Объявления</p>
                <div class="category">
                    <img class="categoryicon" src="~/img/iconlib.png" alt="icon">
                    <a asp-area="" asp-controller="Home" asp-action="Library"><div class="button1 button2" id="libbutton">@Config.gallery0</div></a>
                </div>
                <div class="category">
                    <img class="categoryicon" src="~/img/iconmark.png" alt="icon">
                    <a asp-area="" asp-controller="Home" asp-action="Market"><div class="button1 button2" id="marketbutton">@Config.gallery1</div></a>
                </div>
            </div>
        </nav>

        <div id="content">
            @RenderBody()
        </div>

        <footer>
        </footer>
    </main>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>