Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PolyBook.Domain;
using PolyBook.Domain.Entities;
using PolyBook.Models;
using PolyBook.Service;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PolyBook.Controllers
{
    public class BooksController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly AppDbContext context;
        public BooksController(DataManager dataManager, AppDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
            this.context = context;
        }

        public IActionResult Book(Guid id)
        {
            Book book = dataManager.Books.GetBookById(id);
            if (book == null) {return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());}
            return View("Book", book);
        }

        [Authorize]
        public IActionResult Edit(Guid id)
        {
            Book entity;
            if (id == default) { entity = new Book(); }
            else
            {
                entity = dataManager.Books.GetBookById(id);
                AppUser CurrentUser = context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
                string UserID = CurrentUser.Id;
                if (entity.OwnerID != Guid.Parse(UserID))
                {
                    if (!User.IsInRole("admin"))
                    {
                        return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
                    }
                }
            }
            return View(entity);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(Book model, IFormFile ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (model.OwnerID == default)
                {
                    AppUser CurrentUser = context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
                    string UserID = CurrentUser.Id;
                    model.OwnerID = Guid.Parse(UserID);
                }
                string BookOwnerID = model.OwnerID.ToString();
                AppUser BookOwner = context.Users.FirstOrDefault(x => x.Id == BookOwnerID);
                model.OwnerName = BookOwner.Name + " " + BookOwner.Surname;
                if (ImageFile != null)
                {
                    model.ImagePath = DateTime.Now.ToString("HHmmss") + BookOwner.Surname + ".png";
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "img/photos/", model.ImagePath), FileMode.Create))
                    {
                        ImageFile.CopyTo(stream);
                    }
                }
                dataManager.Books.SaveBook(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            AppUser CurrentUser = context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
            Book CurrentBook = context.Books.FirstOrDefault(x => x.Id == id);
            string UserID = CurrentUser.Id;

            if (CurrentBook.OwnerID != Guid.Parse(UserID))
            {
                if (!User.IsInRole("admin"))
                {
                    return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
                }
            }

            dataManager.Books.DeleteBook(CurrentBook);
            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }
    }
}

Views/Shared/Components/EditButton/EditButtonViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using PolyBook.Domain;
using PolyBook.Domain.Entities;
using PolyBook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PolyBook.Views.Shared.Components
{
    public class EditButtonViewComponent : ViewComponent
    {
        private readonly AppDbContext context;
        public EditButtonViewComponent(AppDbContext context)
        {
            this.context = context;
        }

        public ViewViewComponentResult Invoke(Book book)
        {
            bool isOwner = false;
            AppUser CurrentUser = context.Users.FirstOrDefault(x => x.UserName == User.Identity.Name);
            string UserID = CurrentUser.Id;
            if (book.OwnerID == Guid.Parse(UserID) || User.IsInRole("admin"))
            {
                isOwner = true;
            }
            return View(new EditButtonViewModel(book, isOwner));
        }

    }
}

Views/Books/Book.cshtml
@model Book

<div class="contentblock">
    <h1 style="width: 533px; margin: 0 auto 10px auto;">@Model.Title</h1>
    <div id="bigpost">
        <img class="photo" src="~/img/photos/@Model.ImagePath" onError="this.src='../../img/photos/0.png'" alt="photo">
        <div class="postinfo">
            <a><b style="display:block; text-align:center;">@Model.OwnerName</b></a>
            <div class="br20"></div>
            <b>
                Книга из раздела
                @{
                    if (Model.BookGallery == 0)
                    { <span style="color:@Config.yellow;">Библиотека</span> }
                    if (Model.BookGallery == 1)
                    { <span style="color:@Config.red;">Маркет</span> }
                }
            </b>
            <div class="br10"></div>
            <b>Автор:</b> @Model.Author<br>
            <b>Год:</b> @Model.Year<br>
            <b>Тематика:</b> @Model.Subject
        </div>
        <div id="bigposttext">@Model.Text</div>
        @if (User.Identity.IsAuthenticated)
        {
            @await Component.InvokeAsync("EditButton", @Model)
        }
    </div>
</div>

Views/Books/Edit.cshtml
@model Book
@{
    string strTitle = "Редактирование";
    ViewBag.Title = strTitle;
}
<div class="contentblock">
    <div style="width:533px; margin: 0 auto;">
        <h1>@strTitle</h1>
        <div>
            <form asp-controller="Books" asp-action="Edit" method="post" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="Date" />
                <input type="hidden" asp-for="ImagePath" />
                <input type="hidden" asp-for="OwnerID"  value="@Model.OwnerID"/>
                <input type="hidden" asp-for="OwnerName"/>

                <div asp-validation-summary="All"></div>

                <div>
                    <label asp-for="Title"></label>
                    <input asp-for="Title" />
                    <!--<span asp-validation-for="Title"></span>-->
                    <div class="br10"></div>
                </div>
                <div>
                    <label>Выберите раздел:</label><br />
                    <input asp-for="BookGallery" id="libradio" type="radio" value="0" />
                    <label for="libradio">Библиотека</label> <br />
                    <input asp-for="BookGallery" id="markradio" type="radio" value="1" />
                    <label for="markradio">Маркет</label> <div class="br10"></div>
                </div>
                <div class="div-box">
                    <label asp-for="Text"></label><br />
                    <textarea asp-for="Text"></textarea>
                    <!--<span asp-validation-for="Text"></span>-->
                    <div class="br10"></div>
                </div>
                <div style="width: 245px;">
                    <label asp-for="ImagePath"></label>
                    <input type="file" name="ImageFile" id="ImageFile" /> <div class="br10"></div>
                    <div>
                        <img class="img-block" src="~/img/photos/@Model.ImagePath" onError="this.src='../../../img/photos/0.png'" />
                    </div>
                </div><div class="br10"></div>
                <div>
                    <label asp-for="Author"></label>
                    <input asp-for="Author" />
                    <div class="br10"></div>
                    <!--<span asp-validation-for="Author"></span>-->
                </div>
                <div>
                    <label asp-for="Year"></label>
                    <input asp-for="Year" type="number" />
                    <div class="br10"></div>
                    <!--<span asp-validation-for="Year"></span>-->
                </div>
                <div>
                    <label asp-for="Subject"></label>
                    <select asp-for="Subject">
                        <option value="Аппаратные средства">Аппаратные средства</option>
                        <option value="Дизайн и верстка">Дизайн и верстка</option>
                        <option value="Игры">Игры</option>
                        <option value="Математика">Математика</option>
                        <option value="Мотивационное">Мотивационное</option>
                        <option value="Программирование">Программирование</option>
                        <option value="Прочее">Прочее</option>
                    </select>
                </div>
                <div class="br20"></div>
                <button style="width: 533px;" class="button1" type="submit">Сохранить</button>
            </form>
        </div>
    </div>
</div>